-- MySQL Script generated by MySQL Workbench
-- Thu 26 May 2016 02:46:10 PM CDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Centro_Idiomas
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Centro_Idiomas` ;

-- -----------------------------------------------------
-- Schema Centro_Idiomas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Centro_Idiomas` DEFAULT CHARACTER SET utf8 ;
USE `Centro_Idiomas` ;

-- -----------------------------------------------------
-- Table `Centro_Idiomas`.`Administradores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Centro_Idiomas`.`Administradores` (
  `idAdministrador` VARCHAR(8) NOT NULL,
  `Nombre` VARCHAR(100) NOT NULL,
  `Apellido_Materno` VARCHAR(50) NOT NULL,
  `Apellido_Paterno` VARCHAR(50) NOT NULL,
  `Contraseña` VARCHAR(16) NOT NULL,
  `Correo` VARCHAR(200) NOT NULL,
  `Status` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idAdministrador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Centro_Idiomas`.`Idiomas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Centro_Idiomas`.`Idiomas` (
  `idIdiomas` VARCHAR(5) NOT NULL,
  `Idioma` VARCHAR(70) NOT NULL,
  `Niveles` DECIMAL(10,0) NOT NULL,
  `Objetivo` TEXT NOT NULL,
  `Perfil_Ingreso` TEXT NOT NULL,
  `Perfil_Egreso` TEXT NOT NULL,
  `Imagen` TEXT NULL,
  PRIMARY KEY (`idIdiomas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Centro_Idiomas`.`Docentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Centro_Idiomas`.`Docentes` (
  `idDocente` VARCHAR(10) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido_Paterno` VARCHAR(45) NOT NULL,
  `Apellido_Materno` VARCHAR(45) NOT NULL,
  `Correo` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDocente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Centro_Idiomas`.`Cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Centro_Idiomas`.`Cursos` (
  `idCursos` INT NOT NULL AUTO_INCREMENT,
  `Nombre_del_Curso` VARCHAR(200) NOT NULL,
  `Nivel` INT NOT NULL,
  `Horario` VARCHAR(45) NOT NULL,
  `salon` VARCHAR(5) NOT NULL,
  `Fec_Inicio_Insc` DATE NOT NULL,
  `Fec_Fin_Insc` DATE NOT NULL,
  `Fecha_Inicio_Curso` DATE NOT NULL,
  `Fecha_Fin_Curso` DATE NOT NULL,
  `Capacidad` INT NULL,
  `Inscritos` INT NULL,
  `Pendientes` INT NULL,
  `Maestros_idMaestros` VARCHAR(10) NOT NULL,
  `Idiomas_idIdiomas` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idCursos`, `Maestros_idMaestros`, `Idiomas_idIdiomas`),
  CONSTRAINT `fk_Cursos_Maestros1`
    FOREIGN KEY (`Maestros_idMaestros`)
    REFERENCES `Centro_Idiomas`.`Docentes` (`idDocente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cursos_Idiomas1`
    FOREIGN KEY (`Idiomas_idIdiomas`)
    REFERENCES `Centro_Idiomas`.`Idiomas` (`idIdiomas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Cursos_Maestros1_idx` ON `Centro_Idiomas`.`Cursos` (`Maestros_idMaestros` ASC);

CREATE INDEX `fk_Cursos_Idiomas1_idx` ON `Centro_Idiomas`.`Cursos` (`Idiomas_idIdiomas` ASC);


-- -----------------------------------------------------
-- Table `Centro_Idiomas`.`Inscripciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Centro_Idiomas`.`Inscripciones` (
  `idInscripciones` INT NOT NULL AUTO_INCREMENT,
  `Fecha_Insc` DATE NULL,
  `Status` TINYINT(1) NULL,
  `N_Control` VARCHAR(45) NULL,
  `Nombre` VARCHAR(45) NULL,
  `Apellido_Paterno` VARCHAR(45) NULL,
  `Apellido_Materno` VARCHAR(45) NULL,
  `Carrera` VARCHAR(45) NULL,
  `Semestre` VARCHAR(45) NULL,
  `Cursos_idCursos` INT NOT NULL,
  PRIMARY KEY (`idInscripciones`, `Cursos_idCursos`),
  CONSTRAINT `fk_Inscripciones_Cursos1`
    FOREIGN KEY (`Cursos_idCursos`)
    REFERENCES `Centro_Idiomas`.`Cursos` (`idCursos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Inscripciones_Cursos1_idx` ON `Centro_Idiomas`.`Inscripciones` (`Cursos_idCursos` ASC);


-- -----------------------------------------------------
-- Table `Centro_Idiomas`.`Examen_Nivelacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Centro_Idiomas`.`Examen_Nivelacion` (
  `idExamen_Nivelacion` INT NOT NULL AUTO_INCREMENT,
  `N_Control` VARCHAR(45) NULL,
  `Nombre` VARCHAR(45) NULL,
  `Apellido_Paterno` VARCHAR(45) NULL,
  `Apellido_Materno` VARCHAR(45) NULL,
  `Carrera` VARCHAR(45) NULL,
  `Semestre` VARCHAR(45) NULL,
  PRIMARY KEY (`idExamen_Nivelacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Centro_Idiomas`.`Publicaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Centro_Idiomas`.`Publicaciones` (
  `idPublicaciones` INT NOT NULL AUTO_INCREMENT,
  `Titulo` TEXT NOT NULL,
  `Contenido` TEXT NOT NULL,
  `Imagen` TEXT NULL,
  `Administradores_idAdministrador` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idPublicaciones`, `Administradores_idAdministrador`),
  CONSTRAINT `fk_Publicaciones_Administradores1`
    FOREIGN KEY (`Administradores_idAdministrador`)
    REFERENCES `Centro_Idiomas`.`Administradores` (`idAdministrador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Publicaciones_Administradores1_idx` ON `Centro_Idiomas`.`Publicaciones` (`Administradores_idAdministrador` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `Centro_Idiomas`.`Administradores`
-- -----------------------------------------------------
START TRANSACTION;
USE `Centro_Idiomas`;
INSERT INTO `Centro_Idiomas`.`Administradores` (`idAdministrador`, `Nombre`, `Apellido_Materno`, `Apellido_Paterno`, `Contraseña`, `Correo`, `Status`) VALUES ('admin', 'Nombre', 'Apellido', 'Apellido', 'Password2016', 'correo@centroidioma.com', 1);
INSERT INTO `Centro_Idiomas`.`Administradores` (`idAdministrador`, `Nombre`, `Apellido_Materno`, `Apellido_Paterno`, `Contraseña`, `Correo`, `Status`) VALUES ('CIIRGDRG', 'Ivan', 'Romero', 'Garcia', 'Newyork1209', 'ivan_archer93@hotmail.com', 0);

COMMIT;


-- -----------------------------------------------------
-- Data for table `Centro_Idiomas`.`Idiomas`
-- -----------------------------------------------------
START TRANSACTION;
USE `Centro_Idiomas`;
INSERT INTO `Centro_Idiomas`.`Idiomas` (`idIdiomas`, `Idioma`, `Niveles`, `Objetivo`, `Perfil_Ingreso`, `Perfil_Egreso`, `Imagen`) VALUES ('CICHI', 'Chino', 1, 'Los estudiantes podrán comprender y aprender una gran cantidad de contenidos relacionados con la vida cotidiana. Serán capaces de manejar patrones oracionales un poco más complejos, hacer descripciones e intercambiar ideas en torno a temas conocidos. \r\nAdemás, estarán en condiciones de construir pasajes y discursos. En este nivel, los estudiantes ya tendrán un claro interés por el idioma chino y tendrán la capacidad de recurrir a estrategias didácticas, comunicativas e interdisciplinarias. De otro lado conocerán sobre la cultura china, tendrán una conciencia intercultural y una perspectiva global construida.', 'Afición por la lectura.\r\nEspíritu abierto e interés por la diversidad y la multiculturalidad.\r\nCapacidad para cooperar con otras personas e instituciones en el desempeño de las labores propias de su profesión.\r\nDotes para la expresión y comunicación de forma adecuada y respetuosa.', 'Tendrá un manejo fluido de la lengua china, sustentado por el conocimiento del marco cultural e histórico.\r\nSerá facilitador del diálogo, conocedor del idioma así como de su uso y de las costumbres propias de la sociedad oriental.\r\nPodrá ofrecer sus servicios a editoriales, periódicos y revistas de amplia divulgación y/o específicas.\r\nSerá agente conocedor de procesadores de textos para la producción textual y comunicación en idioma chino.\r\nSerá interlocutor capaz de incorporarse al ámbito empresarial y cultural.', 'image/idiomas/20160525100853.png');
INSERT INTO `Centro_Idiomas`.`Idiomas` (`idIdiomas`, `Idioma`, `Niveles`, `Objetivo`, `Perfil_Ingreso`, `Perfil_Egreso`, `Imagen`) VALUES ('CIFRA', 'Francés', 4, 'Tiene como objetivo primordial preparar profesionistas que dominen las cuatro habilidades lingüísticas en francés y posean una sólida formación profesional y humanista. \r\nEsta formación desarrollará en los egresados la competencia para entender la complejidad de los problemas sociales, económicos, culturales y políticos del mundo actual y para poder resolverlos con responsabilidad y eficiencia.', 'Que tenga aprecio por los idiomas y las manifestaciones culturales propias y ajenas, inclinación por la lectura y la investigación y disposición para el aprendizaje autónomo y el uso de las nuevas tecnologías. \r\nDeberá contar también con habilidades para el discurso y para la comprensión, tanto en lo oral como por escrito, y haber desarrollado un pensamiento analítico-crítico y capacidad de abstracción.', 'Los egresados deberán dominar la expresión oral y escrita tanto en español como en francés.\r\nLos conocimientos adquiridos y las aptitudes y actitudes desarrolladas a lo largo del curso habrán definido a un individuo de alta calidad moral y pensamiento crítico, preparado para actuar, desde su ámbito, en beneficio de la sociedad.', 'image/idiomas/20160525095916.png');
INSERT INTO `Centro_Idiomas`.`Idiomas` (`idIdiomas`, `Idioma`, `Niveles`, `Objetivo`, `Perfil_Ingreso`, `Perfil_Egreso`, `Imagen`) VALUES ('CIING', 'Inglés', 5, 'Formar estudiante con habilidad para poder desarrollarse en un ambiente donde el idioma sea el ingles.\r\nEl estudiante aplicara de manera fluida cuatro habilidades habla, escribir, leer y escuchar que serán adquiridas a través de enseñanza-aprendizaje que buscan desarrollar las competencias comunicativas de los estudiantes en el idioma inglés.', 'Estudiantes de nivel superior interesados en aprender ingles y emplearlo en un ambiente laboral y social.\r\nProfesionistas que requieran comunicarse hablando y escribiendo en inglés en diversos contextos laborales.', 'Ser capaz de participar en conversaciones con cierta fluidez sobre diversos temas de la actualidad.\r\nEscribir y leer textos sobre sobre temas de interes con el objetivo de obtener informacion y poder defender sus ideales.', 'image/idiomas/20160524093325.png');
INSERT INTO `Centro_Idiomas`.`Idiomas` (`idIdiomas`, `Idioma`, `Niveles`, `Objetivo`, `Perfil_Ingreso`, `Perfil_Egreso`, `Imagen`) VALUES ('CIITA', 'Italiano', 1, 'Formar profesionales críticos y reflexivos que comprendan, interpreten, comuniquen y difundan los idioma italiano desde una perspectiva interdisciplinaria con visión innovadora y amplia cultura que le permitan desarrollarse con ética y calidad en los campos de la docencia o la traducción.', 'Disposición e interés hacia el aprendizaje de idiomas.\r\nCapacidad de comunicarse de manera oral y escrita en lo cotidiano en el español\r\nRespeto por su cultura y apertura a otras culturas.\r\nCapacidad para adquirir conocimiento de diversas áreas de estudio.', 'Aplicar de manera eficiente los conocimientos declarativos y procedimentales relacionados con la producción del italiano como segundas lenguas.\r\nAplicar las habilidades didácticas para favorecer el aprendizaje de una segunda lengua a través de asignaturas de contenido teórico y de asignaturas de lenguas extranjeras.\r\nAplicar las habilidades didácticas para promover el uso de las tecnologías de la información y la comunicación en diferentes contextos de enseñanza aprendizaje.', 'image/idiomas/20160525102607.png');

COMMIT;


-- -----------------------------------------------------
-- Data for table `Centro_Idiomas`.`Docentes`
-- -----------------------------------------------------
START TRANSACTION;
USE `Centro_Idiomas`;
INSERT INTO `Centro_Idiomas`.`Docentes` (`idDocente`, `Nombre`, `Apellido_Paterno`, `Apellido_Materno`, `Correo`, `Telefono`) VALUES ('CIJBLL2J', 'Julio', 'Beltran', 'Lopez', 'julio_MI@itver.com', '2290234563');
INSERT INTO `Centro_Idiomas`.`Docentes` (`idDocente`, `Nombre`, `Apellido_Paterno`, `Apellido_Materno`, `Correo`, `Telefono`) VALUES ('CIEMRX4K', 'Emanuel', 'Morales', 'Rergis', 'emanuel_mr@itver.com', '2292925461');
INSERT INTO `Centro_Idiomas`.`Docentes` (`idDocente`, `Nombre`, `Apellido_Paterno`, `Apellido_Materno`, `Correo`, `Telefono`) VALUES ('CIECLZO1', 'Elías A.', 'Castillo', 'Lezama', 'elias_cl@itver.com', '2292541231');
INSERT INTO `Centro_Idiomas`.`Docentes` (`idDocente`, `Nombre`, `Apellido_Paterno`, `Apellido_Materno`, `Correo`, `Telefono`) VALUES ('CIVLTI3W', 'Virginia', 'Llanera', 'Tejeda', 'virginia_lt@itver.com', '2292217812');

COMMIT;


-- -----------------------------------------------------
-- Data for table `Centro_Idiomas`.`Cursos`
-- -----------------------------------------------------
START TRANSACTION;
USE `Centro_Idiomas`;
INSERT INTO `Centro_Idiomas`.`Cursos` (`idCursos`, `Nombre_del_Curso`, `Nivel`, `Horario`, `salon`, `Fec_Inicio_Insc`, `Fec_Fin_Insc`, `Fecha_Inicio_Curso`, `Fecha_Fin_Curso`, `Capacidad`, `Inscritos`, `Pendientes`, `Maestros_idMaestros`, `Idiomas_idIdiomas`) VALUES (1, 'Inglés Basico 1', 1, '08:00 – 09:00', 'D', '2016-04-16', '2016-04-16', '2016-04-16', '2016-04-16', 20, 0, 0, 'CIECLZO1', 'CIING');

COMMIT;


-- -----------------------------------------------------
-- Data for table `Centro_Idiomas`.`Publicaciones`
-- -----------------------------------------------------
START TRANSACTION;
USE `Centro_Idiomas`;
INSERT INTO `Centro_Idiomas`.`Publicaciones` (`idPublicaciones`, `Titulo`, `Contenido`, `Imagen`, `Administradores_idAdministrador`) VALUES (1, 'Becas de capacitacion verano sep TecNM Banamex Canieti 2016.', 'Convoca a los estudiantes de los institutos tenologicos del pais que esten inscritos a partir del 8 semestre en las carreras del area de ingenieria:\r\nA solicitar una Beca de Capacitacion para realizar estudios del idioma de ingles y preparacion para los examenes TOEFI y GRE en los Estados Unidos de America con el objeto de fortalecer sun formacion profesional, dotandolos de herramientas que le permitan en un futuro cursas un programa de maestria en universidad de Estados Unidos de America en areas relacionadas con las tecnologias mas inovadoras y de mayor vanguardia del sector de la electronica, telecomunicaciones y tecnologia de la Informacion.', 'image/publicaciones/20160525032735.jpg', 'CIIRGDRG');
INSERT INTO `Centro_Idiomas`.`Publicaciones` (`idPublicaciones`, `Titulo`, `Contenido`, `Imagen`, `Administradores_idAdministrador`) VALUES (2, 'Convocatoria Talento SEP', 'Talento de Educacion Media Superior Convioca:\r\nA todos los alumnos que deseen participar en el programa de BecaTalento de la SEP como tutores de alumnos de Educacion Media Superior.\r\nRequisitos:\r\nContar con un promedio minimo de 80.\r\nSer de 6,7,8,9 semestre.\r\nContar con la disponibilidad los dias sabado.\r\nInterezados presentarse en el depto. De desarrollo academico con la impresion de su kardex en el horario de 12 a6 pm con la maestra Maria Yepez.\r\nEvaluacion Docente ene- jun 2016.', 'image/publicaciones/20160525040015.jpg', 'CIIRGDRG');

COMMIT;

