-- MySQL Script generated by MySQL Workbench
-- lun 18 abr 2016 17:03:00 CDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Centro_Idiomas
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Centro_Idiomas` ;

-- -----------------------------------------------------
-- Schema Centro_Idiomas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Centro_Idiomas` DEFAULT CHARACTER SET utf8 ;
USE `Centro_Idiomas` ;

-- -----------------------------------------------------
-- Table `Centro_Idiomas`.`Administradores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Centro_Idiomas`.`Administradores` (
  `idAdministrador` VARCHAR(8) NOT NULL,
  `Nombre` VARCHAR(100) NOT NULL,
  `Apellido_Materno` VARCHAR(50) NOT NULL,
  `Apellido_Paterno` VARCHAR(50) NOT NULL,
  `Contraseña` VARCHAR(16) NOT NULL,
  `Correo` VARCHAR(200) NOT NULL,
  `status` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idAdministrador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Centro_Idiomas`.`Idiomas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Centro_Idiomas`.`Idiomas` (
  `idIdiomas` INT NOT NULL AUTO_INCREMENT,
  `Idiomas` VARCHAR(70) NOT NULL,
  `Niveles` DECIMAL(10,0) NOT NULL,
  `Descripcion` TEXT NOT NULL,
  PRIMARY KEY (`idIdiomas`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
